version: 2
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring

    docker:
      - image: circleci/openjdk:8-jdk-browsers
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

    steps:

      - checkout

      - restore_cache:
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn dependency:go-offline
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-demo-java-spring-{{ checksum "pom.xml" }}
      
      - run: mvn package
      - run: cat target/surefire-reports/TEST-com.circleci.demojavaspring.DemoJavaSpringApplicationTests.xml
      - run: cat target/surefire-reports/com.circleci.demojavaspring.DemoJavaSpringApplicationTests.txt
      
      - store_test_results:
          path: targett/surefire-reports
          
      - store_artifacts:
          path: target/demo-java-spring-0.0.1-SNAPSHOT.jar
